# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from chatbot_manager.models.base_model_ import Model
from chatbot_manager import util


class ChatbotBasicInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, description: str=None):  # noqa: E501
        """ChatbotBasicInfo - a model defined in Swagger

        :param id: The id of this ChatbotBasicInfo.  # noqa: E501
        :type id: str
        :param description: The description of this ChatbotBasicInfo.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description'
        }

        self._id = id
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'ChatbotBasicInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatbotBasicInfo of this ChatbotBasicInfo.  # noqa: E501
        :rtype: ChatbotBasicInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ChatbotBasicInfo.


        :return: The id of this ChatbotBasicInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ChatbotBasicInfo.


        :param id: The id of this ChatbotBasicInfo.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this ChatbotBasicInfo.


        :return: The description of this ChatbotBasicInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ChatbotBasicInfo.


        :param description: The description of this ChatbotBasicInfo.
        :type description: str
        """

        self._description = description
