# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, running: bool=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param running: The running of this Body.  # noqa: E501
        :type running: bool
        """
        self.swagger_types = {
            'running': bool
        }

        self.attribute_map = {
            'running': 'running'
        }

        self._running = running

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def running(self) -> bool:
        """Gets the running of this Body.


        :return: The running of this Body.
        :rtype: bool
        """
        return self._running

    @running.setter
    def running(self, running: bool):
        """Sets the running of this Body.


        :param running: The running of this Body.
        :type running: bool
        """

        self._running = running
