# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ChatbotBasicInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, descrption: str=None):  # noqa: E501
        """ChatbotBasicInfo - a model defined in Swagger

        :param id: The id of this ChatbotBasicInfo.  # noqa: E501
        :type id: str
        :param descrption: The descrption of this ChatbotBasicInfo.  # noqa: E501
        :type descrption: str
        """
        self.swagger_types = {
            'id': str,
            'descrption': str
        }

        self.attribute_map = {
            'id': 'id',
            'descrption': 'descrption'
        }

        self._id = id
        self._descrption = descrption

    @classmethod
    def from_dict(cls, dikt) -> 'ChatbotBasicInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatbotBasicInfo of this ChatbotBasicInfo.  # noqa: E501
        :rtype: ChatbotBasicInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ChatbotBasicInfo.


        :return: The id of this ChatbotBasicInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ChatbotBasicInfo.


        :param id: The id of this ChatbotBasicInfo.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def descrption(self) -> str:
        """Gets the descrption of this ChatbotBasicInfo.


        :return: The descrption of this ChatbotBasicInfo.
        :rtype: str
        """
        return self._descrption

    @descrption.setter
    def descrption(self, descrption: str):
        """Sets the descrption of this ChatbotBasicInfo.


        :param descrption: The descrption of this ChatbotBasicInfo.
        :type descrption: str
        """

        self._descrption = descrption
